# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

**Please note again that we are using 0 to represent heads, and 1 to represent tails.**

In [5]:
# import numpy
import numpy as np


### 1. Two fair coin flips produce exactly two heads

In [6]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))
tests

array([[0, 0],
       [0, 0],
       [1, 1],
       ...,
       [1, 0],
       [1, 1],
       [1, 0]])

#### ※ random.randint(low, high=None, size=None, dtype=int)
    Return random integers from low (inclusive) to high (exclusive).   
    randint(최저값, 최고값, 배열크기, 데이터타입)



In [7]:
# sums of all tests
test_sums = tests.sum(axis=1)  #axis=1 : 행끼리 sum / axis=0 : 열끼리 sum
test_sums

array([0, 0, 2, ..., 1, 2, 1])

In [8]:
# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250162

### 2. Three fair coin flips produce exactly one head

In [9]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6),3))
tests

array([[0, 1, 1],
       [0, 0, 0],
       [1, 0, 0],
       ...,
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
# sums of all tests
test_sums = tests.sum(axis=1)
test_sums

array([2, 0, 1, ..., 1, 3, 3])

In [11]:
# proportion of tests that produced exactly one head
(test_sums==2).mean()

0.37515

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [12]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()
tests = np.random.choice(2, size=(int(1e6),3), p=[0.6, 0.4])
tests

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       ...,
       [1, 0, 1],
       [1, 1, 1],
       [0, 0, 0]])

#### ※ random.choice(a, size=None, replace=True, p=None)
    Generates a random sample from a given 1-D array
    a는 1-D-array 이거나 int. int인 경우 np.arrange(a)와 같이 정수 0부터 a까지의 숫자 배열이 됨. 
    p는 각 배열값에 적용할 확률. 생략한 경우 동일한 확률로 적용됨. 

In [13]:
# sums of all tests
test_sums = tests.sum(axis=1)
test_sums


array([1, 0, 1, ..., 2, 3, 0])

In [14]:
# proportion of tests that produced exactly one head
(test_sums==2).mean()

0.2878

### 4. A die rolls an even number

In [23]:
# simulate 1 million tests of one die roll
## tests = np.random.randint(6,size=(int(1e6),1)) #이렇게 쓰면 [0,1,2,3,4,5] 가 되기 때문에.. 아래처럼 choice()를 사용해서 1~6까지로 설정해줌. 
tests = np.random.choice(np.arange(1,7),size=(int(1e6),1))
tests

array([[5],
       [5],
       [6],
       ...,
       [5],
       [6],
       [3]])

In [24]:
# proportion of tests that produced an even number
(tests%2==0).mean()

0.499209

### 5. Two dice roll a double

In [26]:
# simulate the first million die rolls
first = np.random.choice(np.arange(6),size=(int(1e6),1))
first

array([[5],
       [3],
       [1],
       ...,
       [0],
       [5],
       [1]])

In [27]:
# simulate the second million die rolls
second = np.random.choice(np.arange(6),size=(int(1e6),1))
second

array([[5],
       [5],
       [0],
       ...,
       [1],
       [4],
       [5]])

In [28]:
# proportion of tests where the 1st and 2nd die rolled the same number
(first==second).mean()

0.166283